### ISSUE TITLE
code-gen crossplane - iam - Group redeclared in this block / other declaration of Group

### ISSUE THREAD

**Issue by haarchri** [aws-controllers-k8s/community#1108]
**Describe the bug**
A concise description of what the bug is.

![image](https://user-images.githubusercontent.com/21083497/146687728-9102e5f4-e326-407c-b585-cb860774b62b.png)

**Steps to reproduce**
create iam generator-config.yaml
make generate

```
20:12:21 [ .. ] go generate darwin_amd64
panic: interface conversion: types.Type is nil, not *types.Named

goroutine 1 [running]:
sigs.k8s.io/controller-tools/pkg/deepcopy.shouldBeCopied(0xc000b86720, 0xc005800ae0, 0x1003501)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/deepcopy/traverse.go:622 +0x374
sigs.k8s.io/controller-tools/pkg/deepcopy.(*ObjectGenCtx).generateForPackage.func1(0xc005800ae0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/deepcopy/gen.go:230 +0xaf
sigs.k8s.io/controller-tools/pkg/markers.EachType.func1(0xc0063ab600, 0xc0055d5580, 0xc0056515f0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/markers/zip.go:179 +0x76e
sigs.k8s.io/controller-tools/pkg/loader.(*typeVisitor).Visit(0xc00579e570, 0x19da2a8, 0xc0056515f0, 0x0, 0x0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/loader/visit.go:64 +0x151
go/ast.Walk(0x19d5340, 0xc00579e570, 0x19da2a8, 0xc0056515f0)
        /Users/haarchri/.gvm/gos/go1.16/src/go/ast/walk.go:52 +0x63
go/ast.Walk(0x19d5340, 0xc00579e570, 0x19d9f10, 0xc0055d5580)
        /Users/haarchri/.gvm/gos/go1.16/src/go/ast/walk.go:331 +0xe89
go/ast.walkDeclList(0x19d5340, 0xc00579e570, 0xc005640800, 0x2a, 0x40)
        /Users/haarchri/.gvm/gos/go1.16/src/go/ast/walk.go:38 +0x9e
go/ast.Walk(0x19d5340, 0xc00579e570, 0x19d9e48, 0xc0063ab600)
        /Users/haarchri/.gvm/gos/go1.16/src/go/ast/walk.go:353 +0x2446
sigs.k8s.io/controller-tools/pkg/loader.EachType(0xc000b86720, 0xc00579e558)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/loader/visit.go:38 +0xaa
sigs.k8s.io/controller-tools/pkg/markers.EachType(0xc00088fcf8, 0xc000b86720, 0xc0057bbd40, 0x8, 0xc0077523e8)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/markers/zip.go:155 +0xa7
sigs.k8s.io/controller-tools/pkg/deepcopy.(*ObjectGenCtx).generateForPackage(0xc00093fb50, 0xc000b86720, 0x0, 0x0, 0x0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/deepcopy/gen.go:220 +0x1e5
sigs.k8s.io/controller-tools/pkg/deepcopy.Generator.Generate(0xc00003f59b, 0x1a, 0x0, 0x0, 0xc0001100a0, 0xc00022f201, 0x2fdde58)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/deepcopy/gen.go:155 +0x1af
sigs.k8s.io/controller-tools/pkg/genall.(*Runtime).Run(0xc0007fbb80, 0xc0001fdb80)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/pkg/genall/genall.go:207 +0x1b7
main.main.func1(0xc000228280, 0xc0001fdb80, 0x4, 0x4, 0x0, 0x0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/cmd/controller-gen/main.go:176 +0xba
github.com/spf13/cobra.(*Command).execute(0xc000228280, 0xc0000300b0, 0x4, 0x4, 0xc000228280, 0xc0000300b0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000228280, 0xc00000ce10, 0x4, 0x0)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        /Users/haarchri/Documents/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-tools@v0.6.2/cmd/controller-gen/main.go:200 +0x346
exit status 2
apis/generate.go:26: running "go": exit status 1
20:12:28 [FAIL]
make[1]: *** [go.generate] Error 1
make: *** [generate] Error 2
```

**Expected outcome**
A concise description of what you expected to happen.

**Environment**
https://github.com/crossplane/provider-aws/issues/479

* Kubernetes version 1.21
* Using EKS 1.21
* AWS service targeted iam

**Comment by vijtrip2** [comment]
Thank you @haarchri
