### ISSUE TITLE
aws-rds-controller latest segfaults on null pointer in surprising line

### ISSUE THREAD

**Issue by doctorpangloss** [aws-controllers-k8s/community#2032]
**Describe the bug**
```
{"level":"info","ts":"2024-03-07T23:24:05.203Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"dbcluster","controllerGroup":"rds.services.k8s.aws","controllerKind":"DBCluster","DBCluster":{"name":"appmana-postgres-production-01","namespace":"appmana"},"namespace":"appmana","name":"appmana-postgres-production-01","reconcileID":"190d567d-bc71-4a2a-a8b2-52b5eb0beb44"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a600ab]

goroutine 246 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:116 +0x1e5
panic({0x1d04520?, 0x3651ee0?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/aws-controllers-k8s/rds-controller/pkg/resource/db_cluster.(*resourceManager).newCustomUpdateRequestPayload(0xc000a81080, {0x2671028, 0xc000bfd0e0}, 0xc0007063b0, 0xc000346b70, 0xc000de62d0)
        /github.com/aws-controllers-k8s/rds-controller/pkg/resource/db_cluster/custom_update.go:583 +0x3cb
github.com/aws-controllers-k8s/rds-controller/pkg/resource/db_cluster.(*resourceManager).customUpdate(0xc000a81080, {0x2671028, 0xc000bfd0e0}, 0xc0007063b0, 0xc000346b70, 0xc000de62d0)
        /github.com/aws-controllers-k8s/rds-controller/pkg/resource/db_cluster/custom_update.go:80 +0x74c
github.com/aws-controllers-k8s/rds-controller/pkg/resource/db_cluster.(*resourceManager).sdkUpdate(...)
        /github.com/aws-controllers-k8s/rds-controller/pkg/resource/db_cluster/sdk.go:1513
github.com/aws-controllers-k8s/rds-controller/pkg/resource/db_cluster.(*resourceManager).Update(0xc000a81080, {0x2671028?, 0xc000bfd0e0?}, {0x267a5a0?, 0xc0007063b0?}, {0x267a5a0?, 0xc000346b70}, 0x5?)
        /github.com/aws-controllers-k8s/rds-controller/pkg/resource/db_cluster/manager.go:157 +0x78
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).updateResource(0xc0006ae1a0, {0x2671028, 0xc000bfd0e0}, {0x267a538, 0xc000a81080}, {0x267a5a0, 0xc0007063b0}, {0x267a5a0, 0xc000346b70})
        /go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.30.0/pkg/runtime/reconciler.go:536 +0x3e3
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).Sync(0xc0006ae1a0, {0x2671028, 0xc000bfd0e0}, {0x267a538, 0xc000a81080}, {0x267a5a0, 0xc000706340})
        /go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.30.0/pkg/runtime/reconciler.go:279 +0x7de
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).reconcile(0xc0006ae1a0, {0x2671028, 0xc000bfd0e0}, {0x267a538, 0xc000a81080}, {0x267a5a0, 0xc000706340})
        /go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.30.0/pkg/runtime/reconciler.go:215 +0x1cd
github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).Reconcile(0xc0006ae1a0, {0x2671028, 0xc000bfc000}, {{{0xc00093c166?, 0x5?}, {0xc00005efa0?, 0xc0001add10?}}})
        /go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.30.0/pkg/runtime/reconciler.go:186 +0x71b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2675768?, {0x2671028?, 0xc000bfc000?}, {{{0xc00093c166?, 0xb?}, {0xc00005efa0?, 0x0?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:119 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0006fc320, {0x2671060, 0xc0000aa820}, {0x1dda220, 0xc0007880e0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:316 +0x3bc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0006fc320, {0x2671060, 0xc0000aa820})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266 +0x1be
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 70
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:223 +0x50c
```
https://github.com/aws-controllers-k8s/rds-controller/blob/7ef102affadee8f7a9fbf41b04e5e2780c9e7268/pkg/resource/db_cluster/custom_update.go#L582C1-L586C3
Observe this CRD does not have `autoMinorVersionUpgrade`
**Steps to reproduce**
Try to set the engineVersion in an Aurora DBCluster, then change it.
**Expected outcome**
Handle this issue gracefully without crashing the controller

**Environment**

* Kubernetes version 1.26.2
* Using EKS (yes/no), if so version? no
* AWS service targeted (S3, RDS, etc.) RDS

**Comment by a-hilaly** [comment]
@doctorpangloss Thank you for reporting this. v1.2.3 is on the way. No the controller will use a default if the field is nil.
