### ISSUE TITLE
[EC2] Panic on invalid memory address or nil pointer deference

### ISSUE THREAD

**Issue by nromriell** [aws-controllers-k8s/community#2063]
**Describe the bug**
During apply of EC2 objects if `value` is missing or nil 
```
Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference
```

Related location in code: https://github.com/aws-controllers-k8s/ec2-controller/blob/main/pkg/resource/elastic_ip_address/hooks.go#L124-L143

Panic stack trace logged by controller
```
ack-ec2-controller-56769676cd-gffv4 controller {"level":"info","ts":"2024-04-24T19:06:58.867Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"elasticipaddress","controllerGroup":"ec2.services.k8s.aws","controllerKind":"ElasticIPAddress","ElasticIPAddress":{"name":"example","namespace":"example"},"namespace":"example","name":"example","reconcileID":"eb00c0d9-3878-4497-86e3-32df23b94ccf"}
ack-ec2-controller-56769676cd-gffv4 controller panic: runtime error: invalid memory address or nil pointer dereference [recovered]
ack-ec2-controller-56769676cd-gffv4 controller 	panic: runtime error: invalid memory address or nil pointer dereference
ack-ec2-controller-56769676cd-gffv4 controller [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1cd148e]
ack-ec2-controller-56769676cd-gffv4 controller
ack-ec2-controller-56769676cd-gffv4 controller goroutine 765 [running]:
ack-ec2-controller-56769676cd-gffv4 controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
ack-ec2-controller-56769676cd-gffv4 controller 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:116 +0x1e5
ack-ec2-controller-56769676cd-gffv4 controller panic({0x209adc0?, 0x3de9b30?})
ack-ec2-controller-56769676cd-gffv4 controller 	/usr/local/go/src/runtime/panic.go:770 +0x132
ack-ec2-controller-56769676cd-gffv4 controller github.com/aws-controllers-k8s/ec2-controller/pkg/resource/elastic_ip_address.computeTagsDelta({0xc0020c0360, 0xb, 0xc001fa8240?}, {0xc0020c03c0, 0xb, 0x18?})
ack-ec2-controller-56769676cd-gffv4 controller 	/github.com/aws-controllers-k8s/ec2-controller/pkg/resource/elastic_ip_address/hooks.go:124 +0xce
ack-ec2-controller-56769676cd-gffv4 controller github.com/aws-controllers-k8s/ec2-controller/pkg/resource/elastic_ip_address.compareTags(0xc001fa8240, 0xc0026aa040, 0xc0026aa048)
ack-ec2-controller-56769676cd-gffv4 controller 	/github.com/aws-controllers-k8s/ec2-controller/pkg/resource/elastic_ip_address/hooks.go:160 +0x73
ack-ec2-controller-56769676cd-gffv4 controller github.com/aws-controllers-k8s/ec2-controller/pkg/resource/elastic_ip_address.newResourceDelta(0xc0026aa040, 0xc0026aa048)
ack-ec2-controller-56769676cd-gffv4 controller 	/github.com/aws-controllers-k8s/ec2-controller/pkg/resource/elastic_ip_address/delta.go:45 +0x8e
ack-ec2-controller-56769676cd-gffv4 controller github.com/aws-controllers-k8s/ec2-controller/pkg/resource/elastic_ip_address.(*resourceDescriptor).Delta(0x2b4c0a0?, {0x2b3e238?, 0xc0026aa040?}, {0x2b3e238?, 0xc0026aa048?})
ack-ec2-controller-56769676cd-gffv4 controller 	/github.com/aws-controllers-k8s/ec2-controller/pkg/resource/elastic_ip_address/descriptor.go:72 +0x45
ack-ec2-controller-56769676cd-gffv4 controller github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).patchResourceMetadataAndSpec(0xc000774c40, {0x2b34730, 0xc003b98270}, {0x2b3e1d0, 0xc00147e9c0}, {0x2b3e238, 0xc002a1ace0}, {0x2b3e238, 0xc002a1ace0})
ack-ec2-controller-56769676cd-gffv4 controller 	/go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.33.0/pkg/runtime/reconciler.go:704 +0x26a
ack-ec2-controller-56769676cd-gffv4 controller github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).lateInitializeResource(0xc000774c40, {0x2b34730, 0xc003b98270}, {0x2b3e1d0, 0xc00147e9c0}, {0x2b3e238, 0xc002a1ace0})
ack-ec2-controller-56769676cd-gffv4 controller 	/go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.33.0/pkg/runtime/reconciler.go:634 +0x258
ack-ec2-controller-56769676cd-gffv4 controller github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).Sync(0xc000774c40, {0x2b34730, 0xc003b98270}, {0x2b3e1d0, 0xc00147e9c0}, {0x2b3e238, 0xc002c6a008})
ack-ec2-controller-56769676cd-gffv4 controller 	/go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.33.0/pkg/runtime/reconciler.go:335 +0x846
ack-ec2-controller-56769676cd-gffv4 controller github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).reconcile(0xc000774c40, {0x2b34730, 0xc003b98270}, {0x2b3e1d0, 0xc00147e9c0}, {0x2b3e238, 0xc002c6a008})
ack-ec2-controller-56769676cd-gffv4 controller 	/go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.33.0/pkg/runtime/reconciler.go:265 +0x1cd
ack-ec2-controller-56769676cd-gffv4 controller github.com/aws-controllers-k8s/runtime/pkg/runtime.(*resourceReconciler).Reconcile(0xc000774c40, {0x2b34730, 0xc00393c780}, {{{0xc003f5e610?, 0x5?}, {0xc0015188d0?, 0xc00066fd10?}}})
ack-ec2-controller-56769676cd-gffv4 controller 	/go/pkg/mod/github.com/aws-controllers-k8s/runtime@v0.33.0/pkg/runtime/reconciler.go:236 +0x7f5
ack-ec2-controller-56769676cd-gffv4 controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2b39068?, {0x2b34730?, 0xc00393c780?}, {{{0xc003f5e610?, 0xb?}, {0xc0015188d0?, 0x0?}}})
ack-ec2-controller-56769676cd-gffv4 controller 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119 +0xb7
ack-ec2-controller-56769676cd-gffv4 controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001aca00, {0x2b34768, 0xc000628c80}, {0x21ccd60, 0xc000e544e0})
ack-ec2-controller-56769676cd-gffv4 controller 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316 +0x3bc
ack-ec2-controller-56769676cd-gffv4 controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001aca00, {0x2b34768, 0xc000628c80})
ack-ec2-controller-56769676cd-gffv4 controller 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266 +0x1be
ack-ec2-controller-56769676cd-gffv4 controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
ack-ec2-controller-56769676cd-gffv4 controller 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227 +0x79
ack-ec2-controller-56769676cd-gffv4 controller created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 169
ack-ec2-controller-56769676cd-gffv4 controller 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:223 +0x50c
- ack-ec2-controller-56769676cd-gffv4 › controller

```

**Steps to reproduce**
Example Elastic IP manifest producing this issue:
```
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: ElasticIPAddress
metadata:
  name: example
spec:
  networkBorderGroup: us-west-2
  publicIPv4Pool: amazon
  tags:
  - key: Test
```
- Apply manifest
- Error is triggered on first controller reconcile of the resource

**Expected outcome**
Controller should not panic when the tag value is empty/nil or crd resource validation should protect against nil values

**Environment**
EKS version: eks.15
Kubernetes Version: 1.27
Service Targeted: EC2
EC2 ACK Controller Version: 1.2.6

**Comment by a-hilaly** [comment]
Hey @nromriell - as a quick work a around please use both keys and values for the tags:
```
  tags:
  - key: Test
    value: ""
```
